[package]
name = "agent_host"  # Matches directory agent_host
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "14.0.0"
wasmtime-wasi = "14.0.0"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1.1"