[package]
name = "simple_increment"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1.1"
sha2 = "0.10"