[package]
name = "simple_increment"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
tokio-tungstenite = "0.20.1"
wasmtime = "13.0.0"
wasm-bindgen = "0.2.89"
anyhow = "1.0.75"
